spring.application.name=Tappr-Backend
server.port=${PORT}

# Database Configuration
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.main.allow-circular-references=true
spring.main.allow-bean-definition-overriding=true

# JWT Configuration
jwt.secret=${JWT_SECRET_KEY}
jwt.expiration=3600000
jwt.refresh-expiration-ms=86400000

spring.config.import=optional:secrets.properties


# ==============================
# Paystack (set these as environment variables)
# ==============================
#paystack.secret-key=${PAYSTACK_SECRET_KEY}
#paystack.public-key=${PAYSTACK_PUBLIC_KEY}
#paystack.base-url=${BASEURL:https://api.paystack.co}

# ==============================
# Mail (set password as environment variable)
# ==============================
# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=465
#spring.mail.port=587
spring.mail.username=twinebravo@gmail.com
spring.mail.password=pspagwvfmhgnwgwu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Smile ID Sandbox Configuration
smile-id.partner-id=YOUR_PARTNER_ID
smile-id.api-key=YOUR_SANDBOX_API_KEY_FROM_PORTAL
smile-id.url=https://testapi.smileidentity.com/v1
smile-id.callback-url=https://your-ngrok-url.com/api/kyc/callback

# SUI microservice
node_service_url="http://localhost:3001/api/sui/derive-address"

reset_password_url="https://tappr.xyz/reset-password?token="