JWT_SECRET_KEY=G++LFCLNKMe/MqiubzY+Y99BYkQ65G8WgLg+5SO5p7M=
PORT=8082
#DATABASE_URL=jdbc:mysql://tappr-chinedunomeh2015-0343.g.aivencloud.com:15747/defaultdb?ssl-mode=REQUIRED
#DATABASE_USERNAME=avnadmin
#DATABASE_PASSWORD=AVNS_Fn4skvjjoX81MTvCJdh


DATABASE_URL=jdbc:mysql://avnadmin:AVNS_weDfxT4XJ6FlDVkzZd0@mysql-7ac2401-chinedunomeh2015-0343.e.aivencloud.com:15747/defaultdb?ssl-mode=REQUIRED
#DATABASE_USERNAME=avnadmin
DATABASE_PASSWORD=AVNS_weDfxT4XJ6FlDVkzZd0
#DATABASE_USERNAME=root
DATABASE_USERNAME=avnadmin


# Mail credentials
MAIL_USERNAME=johdanike@gmail.com
MAIL_PASSWORD=kdsgmniuxcuoobga
